### ISSUE TITLE
Would this code/pattern be usable in a cloudflare worker?

### ISSUE THREAD

**Issue by garrettjoecox** [timvisee/lazymc#13]
Really cool project, only downside is in its current state I’d still have to pay for something always, I’m wondering if this pattern could be used in cloudflare workers or AWS lambdas so that you are only charged on invocations. (Granted I’m not super familiar with either of those technologies and their limitations)

**Comment by timvisee** [comment]
I'm not sure about Lambda or Cloudflare Workers, since I have no real experience with them.

However, if spawning an instance running your Minecraft server can be arranged through a script, this likely is possible. You'd simply provide the script as 'server command' to lazymc after which it should bring up the instance. In this case it doesn't matter on what sort of platform you run.

Another user suggested to implement Terraform support, which would probably streamline this process. Though this isn't implemented, you can read about it here: https://github.com/timvisee/lazymc/discussions/5

Note that when using such configuration, you'd still a machine that's always active to run lazymc itself.

**Comment by garrettjoecox** [comment]
My thought is to combine this pattern with https://github.com/doctorray117/minecraft-ondemand which runs the server on fargate and EFS. 

That repo has a similar setup in that it doesn’t run until you want it to, but simply pinging the server in the server list will spin it up and it shows as offline for the 5 or so minutes it takes to spin up, rather than displaying a friendly message that it is spinning up.

**Comment by timvisee** [comment]
> That repo has a similar setup in that it doesn’t run until you want it to, but simply pinging the server in the server list will spin it up and it shows as offline for the 5 or so minutes it takes to spin up

If lazymc is put in between the server will probably respond much quicker as it starts instantly, without the need for the Minecraft server to be running. It could in turn start the Minecraft server on launch with `wake_on_start = true`.

In any case, these services handle listening on a part and starting the service up for you on socket activity. With lazymc you likely want to keep it running all the time and arrange starting an instance yourself, as it's much more user friendly. In such configuration you could also use traditional cloud services.

Sadly I don't have time right now to experiment with this to create a proof of concept.

**Comment by garrettjoecox** [comment]
Will revisit this issue to experiment once cloudflare releases their socket worker functionality.
