### ISSUE TITLE
Keep alive when using portal chunk loading?

### ISSUE THREAD

**Issue by mmodrow** [timvisee/lazymc#31]
I don't know, how much insight into the world state and events within the server lazyMC actually has, but I was thinking about chunk loaders recently. I am about to build redstone machines on my server, that could break upon uncontrolled unloading. So I will add portal chunk loaders to keep the area loaded.

As of my current understanding this would not prevent the server from shutting down, if no one is connected. Currently I keep an afk player on via the minecraft console client, but if they get disconnected for any reason (or are no good option in the case) the server will still shut down.

Is there any way (or could one be added) to build something in-game to keep the server running until the redstone is finished?

**Comment by timvisee** [comment]
> I don't know, how much insight into the world state and events within the server lazyMC actually has (...)

As little as possible.

The current version has no functionality for this. I believe there are three things you can do right now depending on what you want:

- Set the sleep time to a high value that exceeds your redstone runtime to prevent the server from sleeping.
- With your idle client connected, kick the client when your redstone logic is done. This may be possible with a redstone signal and a command block after your logic is completed. This doesn't, of course, solve the problem of your idle client disconnecting.
- Without the idle client you may be able to `/stop` the server through a command block after your redstone logic is done. When setting `wake_on_crash = false`, the server won't automatically restart unless you reconnect.
  https://github.com/timvisee/lazymc/blob/c6f860f01332d15481924e32d684b6f2f5b600b8/res/lazymc.toml#L39-L40

If you don't want the server to automatically restart when reconnecting, you can also use the last method without `lazymc`.

I hope any of these three approaches are helpful!

By the way, `lazymc` knows as little about the server as possible of constant API changes in every new Minecraft version,. It would otherwise be a lot of work to keep the tool compatible.

**Comment by mmodrow** [comment]
Thanks for the info. In this case I will combine long timeouts with the cli player.

Thanks fox explaining in detail.
