### ISSUE TITLE
LazyMC Transport Endpoint Connection Warning

### ISSUE THREAD

**Issue by WarpWing** [timvisee/lazymc#4]
Hi! I got a warning by lazymc saying
```bash
 Failed to proxy: Transport endpoint is not connected (os error 107)
 ```
What does that mean. Does it mean it's not proxying correctly. In a nutshell, do I need to worry about it?

**Comment by timvisee** [comment]
> In a nutshell, do I need to worry about it?

Likely not.

Since this does networking over the internet (assuming remote clients are connecting) there's many things that can go wrong. Think of clients suddenly disconnecting/disappearing, clients sending malformed data. That's _normal_.

At this moment, I print all connection/proxy failures as a warning, which easily happen because of the above. Since the project is in such an early stage it may be useful for development, even though these very likely aren't problematic cases.

If you aren't experiencing any problems during play, there's nothing to worry about.

Closing this now. Feel free to open this again if an issue arises.

**Comment by WarpWing** [comment]
> 
> 
> > In a nutshell, do I need to worry about it?
> 
> Likely not.
> 
> Since this does networking over the internet (assuming remote clients are connecting) there's many things that can go wrong. Think of clients suddenly disconnecting/disappearing, clients sending malformed data. That's _normal_.
> 
> At this moment, I print all connection/proxy failures as a warning, which easily happen because of the above. Since the project is in such an early stage it may be useful for development, even though these very likely aren't problematic cases.
> 
> If you aren't experiencing any problems during play, there's nothing to worry about.
> 
> Closing this now. Feel free to open this again if an issue arises.

Sweet! Thanks for getting back to me :).
