### ISSUE TITLE
[Suggestion] WebGUI to start the Server

### ISSUE THREAD

**Issue by SkyKingPX** [timvisee/lazymc#63]
It would be great, if you could start the Server through a WebGUI as well as stop and restart it.

**Comment by timvisee** [comment]
Though I like the idea, it goes a bit beyond the main purpose of this project: automatically starting when someone connects.

I believe there are many other tools which can be used to manage Minecraft servers with a web interface.

**Comment by SkyKingPX** [comment]
I know, there are other tools and I already use one, but it doesn’t seem like I am welcomed in the issues, so I don’t want to use it anymore…

**Comment by timvisee** [comment]
Though I'd love to add something like this, sadly I don't have the bandwidth to do so at this time.

My suggestion of looking at other tools wasn't meant as flat out rejection of the idea. Instead it was my attempt of finding a solution elsewhere, because I'm currently unable to implement this myself.

Sorry for being unclear about that.

**Comment by SkyKingPX** [comment]
Ok
