### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by NyaomiDEV** [timvisee/lazymc#64]
While I know Minecraft development is slow, I can't help but wonder if this project is maintained and if it is still going to be in the future.

Issues like #57 and #61 are showstoppers in new adoptions, and as I am searching for a solution to this problem, this project still seems like the perfect fit- the problem is, it seems to not work on 1.20.4.

**Comment by unizippro** [comment]
https://github.com/timvisee/lazymc/issues/57#issuecomment-1951460443 mentions an alternative being [Minecraft Server Hibernation](https://github.com/gekware/minecraft-server-hibernation).
I run this with an old server but thinking of changing over, as lazymc does not seem to shut down the papermc process when sleeping meaning it still takes up memory..

**Comment by NyaomiDEV** [comment]
> [#57 (comment)](https://github.com/timvisee/lazymc/issues/57#issuecomment-1951460443) mentions an alternative being [Minecraft Server Hibernation](https://github.com/gekware/minecraft-server-hibernation). I run this with an old server but thinking of changing over, as lazymc does not seem to shut down the papermc process when sleeping meaning it still takes up memory..

MSH kicks the player with a "try again later" message, while Lazymc has support for holding players until the server's up, which results in better user experience as the player will effectively connect to the server once it's started.

**Comment by timvisee** [comment]
> I can't help but wonder if this project is maintained and if it is still going to be in the future.

Not actively. I don't play Minecraft anymore and have a lot of other work to do, which is why it doesn't get as much love as it did before.

This weekend I'll try to pick it up again to make 1.20.4+ work. Judging by a 3rd party implementation this upgrade does not seem to be very difficult. :+1:

Ideally the Minecraft protocol should be stable, in which case there should not be any breakage across versions. Sadly this doesn't seem to be the case in practice, and there are constant core changes across new versions.

Of course, the project is also open for contributions. So if someone has some spare time and feels confident, please feel free to improve as well. :smile:

**Comment by timvisee** [comment]
I've just released [lazymc 0.2.11](https://github.com/timvisee/lazymc/releases/tag/v0.2.11) which support Minecraft 1.20.3 and up.

**Comment by unizippro** [comment]
> while Lazymc has support for holding players until the server's up
@NyaomiDEV 

This is not my expirience, it will hold for some time, but kick you with a "Server is starting" message.

**Comment by NyaomiDEV** [comment]
> This is not my expirience, it will hold for some time, but kick you with a "Server is starting" message.

@unizippro Is your server fast enough at startup? There is a timeout period where Lazymc *has to* drop players, and that's close to a minute iirc. If you run a modded server that starts in more than that then it's understandable you never saw that behavior.
